# Generated by Django 5.0 on 2024-09-24 12:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grades', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_absent', models.IntegerField(default=0)),
                ('days_late', models.IntegerField(default=0)),
                ('attendance_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('year_end_report', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('grade', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='grades.grade')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='schools.school')),
            ],
            options={
                'ordering': ['-term__start_date'],
            },
        ),
    ]
