# Generated by Django 5.0 on 2024-09-24 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('grades', '0001_initial'),
        ('schools', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='baseuser',
            name='unique_account_email_address',
        ),
        migrations.RenameField(
            model_name='baseuser',
            old_name='email',
            new_name='email_address',
        ),
        migrations.AlterField(
            model_name='admin',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='principal',
            name='contact_number',
            field=models.CharField(max_length=15, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='principal',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='principal', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='grades.grade'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_number',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='ID number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_number',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='passport number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='schools.school'),
        ),
        migrations.AddConstraint(
            model_name='baseuser',
            constraint=models.UniqueConstraint(fields=('email_address',), name='unique_account_email_address'),
        ),
        migrations.AddConstraint(
            model_name='principal',
            constraint=models.UniqueConstraint(fields=('contact_number',), name='unique_account_contact_number'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('id_number',), name='unique_account_id_number'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('passport_number',), name='unique_account_passport_number'),
        ),
    ]
