# Generated by Django 5.0 on 2024-09-24 12:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VIEW', 'View'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('SUBMIT', 'Submit'), ('GRADE', 'Grade'), ('LINK', 'Link'), ('UNLINK', 'Unlink')], max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('target_model', models.CharField(choices=[('ACCOUNT', 'Account'), ('AUDIT_ENTRY', 'Audit Entry'), ('GRADE', 'Grade'), ('TERM', 'Term'), ('SUBJECT', 'Subject'), ('CLASSROOM', 'Classroom'), ('ATTENDANCE', 'Attendance'), ('ANNOUNCEMENT', 'Announcement'), ('ASSESSMENT', 'Assessment'), ('DAILY_SCHEDULE', 'Daily Schedule'), ('GROUP_TIMETABLE', 'Group Timetable'), ('TEACHER_TIMETABLE', 'Teacher Timetable')], max_length=32)),
                ('target_object_id', models.CharField(max_length=36, null=True)),
                ('outcome', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('DELETED', 'Deleted'), ('SUBMITED', 'Submited'), ('GRADED', 'Graded'), ('DENIED', 'Denied'), ('ERROR', 'Error'), ('LINKED', 'Linked'), ('UNLINKED', 'Unlinked')], max_length=32)),
                ('response', models.TextField()),
                ('audit_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
