# Generated by Django 5.0 on 2024-09-24 12:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_set', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('dead_line', models.DateTimeField()),
                ('title', models.CharField(max_length=124)),
                ('assessment_type', models.CharField(choices=[('EXAMINATION', 'Examination'), ('TEST', 'Test'), ('PRACTICAL', 'Practical'), ('ASSIGNMENT', 'Assignment'), ('HOMEWORK', 'Homework'), ('QUIZ', 'Quiz'), ('PROJECT', 'Project'), ('PRESENTATION', 'Presentation'), ('LAB_WORK', 'Lab Work'), ('FIELD_TRIP', 'Field Trip'), ('GROUP_WORK', 'Group Work'), ('SELF_ASSESSMENT', 'Self Assessment'), ('PEER_ASSESSMENT', 'Peer Assessment'), ('PORTFOLIO', 'Portfolio'), ('RESEARCH_PAPER', 'Research Paper'), ('CASE_STUDY', 'Case Study'), ('DISCUSSION', 'Discussion'), ('DEBATE', 'Debate'), ('ROLE_PLAY', 'Role Play'), ('SIMULATION', 'Simulation'), ('ESSAY', 'Essay'), ('MULTIPLE_CHOICE', 'Multiple Choice'), ('OBSERVATION', 'Observation'), ('INTERVIEW', 'Interview'), ('DIAGNOSTIC', 'Diagnostic'), ('FORMATIVE', 'Formative'), ('SUMMATIVE', 'Summative')], default='TEST', max_length=124)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('formal', models.BooleanField(default=False)),
                ('percentage_towards_term_mark', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('collected', models.BooleanField(default=False)),
                ('date_collected', models.DateTimeField(blank=True, null=True)),
                ('grades_released', models.BooleanField(default=False)),
                ('date_grades_released', models.DateTimeField(blank=True, null=True)),
                ('pass_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('failure_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('highest_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lowest_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('average_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('median_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mode_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('percentile_distribution', models.JSONField(blank=True, null=True)),
                ('standard_deviation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('interquartile_range', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('completion_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('assessment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'ordering': ['-dead_line'],
            },
        ),
    ]
