# Generated by Django 5.0 on 2024-09-24 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('classrooms', '0001_initial'),
        ('grades', '0001_initial'),
        ('schools', '0001_initial'),
        ('subjects', '0001_initial'),
        ('terms', '0001_initial'),
        ('topics', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='assessor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessed_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='classrooms.classroom'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='grades.grade'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_moderated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='schools.school'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='students_who_failed_the_assessment',
            field=models.ManyToManyField(help_text='Students who failed the assessment.', related_name='failed_assessments', to='users.student'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='terms.term'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='top_performers',
            field=models.ManyToManyField(blank=True, related_name='top_performers_assessments', to='users.student'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='topics',
            field=models.ManyToManyField(related_name='assessments', to='topics.topic'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['subject', 'grade', 'school'], name='assessments_subject_cd0595_idx'),
        ),
    ]
