# Generated by Django 5.0 on 2024-09-24 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='classrooms.classroom'),
        ),
    ]
