# Generated by Django 5.0 on 2024-09-24 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendances', '0001_initial'),
        ('classrooms', '0001_initial'),
        ('schools', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='absent_students',
            field=models.ManyToManyField(related_name='absences', to='users.student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='classrooms.classroom'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='late_students',
            field=models.ManyToManyField(related_name='late_arrivals', to='users.student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='school',
            field=models.ForeignKey(editable=False, help_text='School to which the attendace belong.', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='schools.school'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencyattendance',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencies', to='classrooms.classroom'),
        ),
        migrations.AddField(
            model_name='emergencyattendance',
            name='missing_students',
            field=models.ManyToManyField(related_name='missing', to='users.student'),
        ),
        migrations.AddField(
            model_name='emergencyattendance',
            name='school',
            field=models.ForeignKey(editable=False, help_text='School to which the emergency belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='emergencies', to='schools.school'),
        ),
        migrations.AddField(
            model_name='emergencyattendance',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_emergencies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'classroom'], name='attendances_date_b7a232_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('date', 'classroom'), name='unique_date_classroom'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('date', 'classroom')},
        ),
        migrations.AddIndex(
            model_name='emergencyattendance',
            index=models.Index(fields=['date'], name='attendances_date_aa6e25_idx'),
        ),
    ]
