# Generated by Django 5.0 on 2024-09-24 12:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('SUBMIT', 'Submit'), ('GENERATE', 'Generate'), ('GRADE', 'Grade'), ('LINK', 'Link'), ('UNLINK', 'Unlink')], max_length=64)),
                ('target_model', models.CharField(choices=[('ACCOUNT', 'Account'), ('GRADE', 'Grade'), ('TERM', 'Term'), ('REPORT_CARD', 'Report Card'), ('SUBJECT', 'Subject'), ('CLASSROOM', 'Classroom'), ('ATTENDANCE', 'Attendance'), ('ANNOUNCEMENT', 'Announcement'), ('ASSESSMENT', 'Assessment'), ('TRANSCRPIT', 'Transcript'), ('DAILY_SCHEDULE', 'Daily Schedule'), ('GROUP_TIMETABLE', 'Group Timetable'), ('TEACHER_TIMETABLE', 'Teacher Timetable')], max_length=64)),
                ('can_execute', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminPermissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('actors_count', models.IntegerField(default=0)),
                ('permissions_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('permission_group_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('SUBMIT', 'Submit'), ('GRADE', 'Grade')], max_length=64)),
                ('target_model', models.CharField(choices=[('ASSESSMENT', 'Assessment'), ('TRANSCRPIT', 'Transcript'), ('ATTENDANCE', 'Attendance')], max_length=64)),
                ('can_execute', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherPermissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('permission_group_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
