# Generated by Django 5.0 on 2024-09-24 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permissions', '0001_initial'),
        ('schools', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpermissiongroup',
            name='actors',
            field=models.ManyToManyField(related_name='permissions', to='users.admin'),
        ),
        migrations.AddField(
            model_name='adminpermissiongroup',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_permission_groups', to='schools.school'),
        ),
        migrations.AddField(
            model_name='adminpermission',
            name='permission_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='permissions.adminpermissiongroup'),
        ),
        migrations.AddField(
            model_name='teacherpermissiongroup',
            name='actors',
            field=models.ManyToManyField(related_name='permissions', to='users.teacher'),
        ),
        migrations.AddField(
            model_name='teacherpermissiongroup',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_permission_groups', to='schools.school'),
        ),
        migrations.AddField(
            model_name='teacherpermission',
            name='permission_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='permissions.teacherpermissiongroup'),
        ),
        migrations.AlterUniqueTogether(
            name='adminpermissiongroup',
            unique_together={('name', 'school')},
        ),
        migrations.AlterUniqueTogether(
            name='teacherpermissiongroup',
            unique_together={('name', 'school')},
        ),
    ]
