# Generated by Django 5.0 on 2024-09-24 12:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('000', 'Grade 000'), ('00', 'Grade 00'), ('R', 'Grade R'), ('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10'), ('11', 'Grade 11'), ('12', 'Grade 12')], editable=False, max_length=4, verbose_name='school grade')),
                ('grade_order', models.PositiveIntegerField()),
                ('student_count', models.IntegerField(default=0)),
                ('major_subjects', models.PositiveIntegerField()),
                ('none_major_subjects', models.PositiveIntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('grade_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='schools.school')),
            ],
            options={
                'ordering': ['grade_order'],
                'indexes': [models.Index(fields=['grade', 'school'], name='grades_grad_grade_b130f0_idx')],
                'unique_together': {('school', 'grade')},
            },
        ),
    ]
