# Generated by Django 5.0 on 2024-09-24 12:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grades', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_number', models.CharField(default='1', max_length=16, verbose_name='classroom identifier')),
                ('group', models.CharField(default='A', max_length=16, verbose_name='class group')),
                ('student_count', models.PositiveIntegerField(default=0)),
                ('pass_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('failure_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('highest_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lowest_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('average_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('median_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('std_dev_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('percentile_distribution', models.JSONField(blank=True, null=True)),
                ('improvement_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('completion_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('register_class', models.BooleanField(default=False, editable=False, help_text='Ensure only one register class per teacher.', verbose_name='is the class a register class')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('classroom_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('grade', models.ForeignKey(editable=False, help_text='Grade level associated with the classroom.', on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='grades.grade')),
                ('school', models.ForeignKey(editable=False, help_text='School to which the classroom belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='schools.school')),
            ],
        ),
    ]
