# Generated by Django 5.0 on 2024-09-24 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0001_initial'),
        ('subjects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(help_text='Students enrolled in the classroom.', related_name='enrolled_classrooms', to='users.student'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='students_failing_the_classroom',
            field=models.ManyToManyField(help_text='Students who are failing the classroom.', related_name='failing_classes', to='users.student'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='subject',
            field=models.ForeignKey(blank=True, editable=False, help_text='Subject taught in the classroom.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='The teacher assigned to the classroom.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_classrooms', to='users.teacher'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='top_performers',
            field=models.ManyToManyField(blank=True, related_name='top_performers_classes', to='users.student'),
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(fields=('group', 'grade', 'subject'), name='unique_group_grade_subject_classroom'),
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(fields=('group', 'grade', 'register_class'), name='unique_group_grade_register_classroom'),
        ),
    ]
