# Generated by Django 5.0 on 2024-09-24 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_subject_performances', '0001_initial'),
        ('subjects', '0001_initial'),
        ('terms', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubjectperformance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_performances', to='users.student'),
        ),
        migrations.AddField(
            model_name='studentsubjectperformance',
            name='subject',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='student_performances', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='studentsubjectperformance',
            name='term',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='student_subject_performances', to='terms.term'),
        ),
        migrations.AddConstraint(
            model_name='studentsubjectperformance',
            constraint=models.UniqueConstraint(fields=('student', 'subject', 'term', 'school'), name='unique_student_subject_term_performance'),
        ),
    ]
