# Generated by Django 5.0 on 2024-09-24 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('progress_reports', '0001_initial'),
        ('student_subject_performances', '0001_initial'),
        ('terms', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='users.student'),
        ),
        migrations.AddField(
            model_name='progressreport',
            name='subject_scores',
            field=models.ManyToManyField(related_name='report', to='student_subject_performances.studentsubjectperformance'),
        ),
        migrations.AddField(
            model_name='progressreport',
            name='term',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='terms.term'),
        ),
        migrations.AddIndex(
            model_name='progressreport',
            index=models.Index(fields=['student', 'term', 'school'], name='progress_re_student_67096d_idx'),
        ),
        migrations.AddConstraint(
            model_name='progressreport',
            constraint=models.UniqueConstraint(fields=('student', 'term', 'grade', 'school'), name='unique_student_term_grade_progress_report'),
        ),
    ]
