# Generated by Django 5.0 on 2024-09-24 12:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comment', models.TextField(blank=True, max_length=1024, null=True)),
                ('weighted_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('moderated_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('moderated_date', models.DateTimeField(blank=True, null=True)),
                ('percentile', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('transcript_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='assessments.assessment')),
            ],
            options={
                'ordering': ['student__surname', 'student__name', 'student__account_id'],
            },
        ),
    ]
