# Generated by Django 5.0 on 2024-09-24 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transcripts', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='users.student'),
        ),
        migrations.AddIndex(
            model_name='transcript',
            index=models.Index(fields=['student', 'assessment'], name='transcripts_student_52f61a_idx'),
        ),
        migrations.AddConstraint(
            model_name='transcript',
            constraint=models.UniqueConstraint(fields=('student', 'assessment'), name='unique_student_assessment_transcript'),
        ),
    ]
