# Generated by Django 5.0 on 2024-09-24 12:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ONTIME', 'On Time'), ('LATE', 'Late'), ('NOT_SUBMITTED', 'Not Submitted'), ('EXCUSED', 'Excused')], default='ONTIME', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('submission_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assessments.assessment')),
            ],
            options={
                'ordering': ['-submission_date'],
            },
        ),
    ]
