# Generated by Django 5.0 on 2024-09-24 12:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grades', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(editable=False, max_length=16)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('school_days', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('term_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('grade', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='grades.grade')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='schools.school')),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['grade', 'school'], name='terms_term_grade_i_ae5a4f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('term', 'grade', 'school'), name='unique_grade_term'),
        ),
    ]
