# Generated by Django 5.0 on 2024-09-24 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('daily_schedule_sessions', '0001_initial'),
        ('daily_schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyschedulesession',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='daily_schedules.dailyschedule'),
        ),
    ]
