# Generated by Django 5.0 on 2024-09-24 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcements', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='announcer',
            field=models.ForeignKey(help_text='User who made the announcement', on_delete=django.db.models.deletion.CASCADE, related_name='my_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='reached',
            field=models.ManyToManyField(help_text='All users who have seen the announcement', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='school',
            field=models.ForeignKey(help_text='School related to the announcement', on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='schools.school'),
        ),
    ]
