# Generated by Django 5.0 on 2024-09-24 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('daily_schedules', '0002_initial'),
        ('teacher_timetables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyschedule',
            name='teacher_timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_schedules', to='teacher_timetables.teachertimetable'),
        ),
    ]
