# Generated by Django 5.0 on 2024-09-24 12:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('reason', models.TextField(verbose_name='reason for banning email')),
                ('can_appeal', models.BooleanField(default=True, verbose_name='can user appeal the ban')),
                ('otp_send', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('BANNED', 'Banned'), ('PENDING', 'Pending'), ('APPEALED', 'Appealed')], default='BANNED', max_length=10, verbose_name='status')),
                ('banned_at', models.DateTimeField(auto_now_add=True, verbose_name='the date the email was banned')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('ban_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
