# Generated by Django 5.0.3 on 2024-03-29 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('established_date', models.DateField(blank=True, null=True)),
                ('accreditation', models.CharField(blank=True, max_length=100, null=True)),
                ('operating_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('academic_calendar', models.TextField(blank=True, null=True)),
                ('principal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_principal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
