# Generated by Django 5.0 on 2024-09-24 12:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='school name')),
                ('email_address', models.EmailField(max_length=254, verbose_name='school email address')),
                ('contact_number', models.CharField(max_length=15, verbose_name='school contact number')),
                ('student_count', models.IntegerField(default=0)),
                ('teacher_count', models.IntegerField(default=0)),
                ('admin_count', models.IntegerField(default=0)),
                ('in_arrears', models.BooleanField(default=False, verbose_name='school bill')),
                ('none_compliant', models.BooleanField(default=False, verbose_name='school denied access')),
                ('type', models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary'), ('HYBRID', 'Hybrid'), ('TERTIARY', 'Tertiary')], default='PRIMARY', max_length=50, verbose_name='school type')),
                ('province', models.CharField(choices=[('GAUTENG', 'Gauteng')], default='GAUTENG', max_length=100, verbose_name='province')),
                ('district', models.CharField(choices=[('GAUTENG EAST', 'Gauteng East'), ('GAUTENG NORTH', 'Gauteng North'), ('GAUTENG WEST', 'Gauteng West'), ('JHB CENTRAL DISTRICT D14', 'JHB Central District D14'), ('JHB NORTH', 'JHB North'), ('JHB WEST', 'JHB West'), ('JHB SOUTH', 'JHB South'), ('JHB EAST', 'JHB EAST'), ('EKURHULENI SOUTH', 'Ekurhuleni South'), ('EKURHULENI NORTH', 'Ekurhuleni North'), ('TSHWANE SOUTH', 'Tshwane South'), ('TSHWANE NORTH', 'Tshwane North'), ('TSHWANE WEST', 'Tshwane West'), ('SEDIBENG EAST', 'Sedibeng East'), ('SEDIBENG WEST', 'Sedibeng West')], default='GAUTENG NORTH', max_length=100, verbose_name='school district')),
                ('grading_system', models.JSONField(blank=True, null=True)),
                ('library_details', models.TextField(blank=True, null=True)),
                ('laboratory_details', models.TextField(blank=True, null=True)),
                ('sports_facilities', models.TextField(blank=True, null=True)),
                ('operating_hours', models.CharField(blank=True, max_length=12, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='school location')),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('school_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='school',
            constraint=models.UniqueConstraint(fields=('email_address',), name='unique_school_email_address'),
        ),
        migrations.AddConstraint(
            model_name='school',
            constraint=models.UniqueConstraint(fields=('contact_number',), name='unique_school_contact_number'),
        ),
    ]
