# Generated by Django 5.0 on 2024-09-24 12:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermSubjectPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('failure_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('highest_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lowest_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('average_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('median_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('standard_deviation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('percentile_distribution', models.JSONField(blank=True, null=True)),
                ('improvement_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('completion_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('term_score_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='termly_subject_performances', to='schools.school')),
            ],
        ),
    ]
