# Generated by Django 5.0 on 2024-09-24 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('term_subject_performances', '0001_initial'),
        ('terms', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsubjectperformance',
            name='students_failing_the_subject_in_the_term',
            field=models.ManyToManyField(help_text='Students who failed the term.', related_name='failing_terms', to='users.student'),
        ),
        migrations.AddField(
            model_name='termsubjectperformance',
            name='subject',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='termly_performances', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='termsubjectperformance',
            name='term',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='subject_performances', to='terms.term'),
        ),
        migrations.AddField(
            model_name='termsubjectperformance',
            name='top_performers',
            field=models.ManyToManyField(blank=True, related_name='top_performers_subject_terms', to='users.student'),
        ),
        migrations.AddConstraint(
            model_name='termsubjectperformance',
            constraint=models.UniqueConstraint(fields=('subject', 'term', 'school'), name='unique_subject_term_performance'),
        ),
    ]
