# Generated by Django 5.0 on 2024-09-24 12:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('ENGLISH', 'English'), ('SEPEDI', 'Sepedi'), ('ZULU', 'Zulu'), ('AFRIKAANS', 'Afrikaans'), ('MATHEMATICS', 'Mathematics'), ('MATHEMATICS LITERACY', 'Mathematics Literacy'), ('TECHNICAL MATHEMATICS', 'Technical Mathematics'), ('PHYSICAL SCIENCE', 'Physical Science'), ('LIFE SCIENCE', 'Life Science'), ('BIOLOGY', 'Biology'), ('GEOGRAPHY', 'Geography'), ('ACCOUNTING', 'Accounting'), ('BUSINESS STUDIES', 'Business Studies'), ('AGRICULTURE', 'Agriculture'), ('TOURISM', 'Tourism'), ('LIFE ORIENTATION', 'Life Orientation'), ('SOCIAL SCIENCE', 'Social Science'), ('ARTS AND CULTURE', 'Arts And Culture')], default='ENGLISH', max_length=64, verbose_name='Subject')),
                ('major_subject', models.BooleanField(default=False)),
                ('pass_mark', models.DecimalField(decimal_places=2, default=40.0, max_digits=5)),
                ('student_count', models.IntegerField(default=0)),
                ('teacher_count', models.IntegerField(default=0)),
                ('classroom_count', models.IntegerField(default=0)),
                ('subject_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='grades.grade')),
            ],
            options={
                'ordering': ['subject'],
                'indexes': [models.Index(fields=['subject', 'grade'], name='subjects_su_subject_d5fab1_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('grade', 'subject'), name='unique_grade_subject'),
        ),
    ]
