# Generated by Django 5.0 on 2024-09-24 12:18

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('billing_date', models.DateField(default=datetime.datetime(2024, 10, 7, 12, 18, 34, 499462, tzinfo=datetime.timezone.utc))),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('balance_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
