# Generated by Django 5.0 on 2024-09-24 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='billing_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 7, 12, 59, 34, 593986, tzinfo=datetime.timezone.utc)),
        ),
    ]
