# Generated by Django 5.0 on 2024-09-24 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0003_alter_balance_billing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='billing_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 7, 14, 52, 7, 202483, tzinfo=datetime.timezone.utc)),
        ),
    ]
